linux: Add missing include
Header file does not directly include a file with the "bool" definition,
leading to erros like:

    include/linux/err.h:33:15: error: unknown type name ‘bool’
      static inline bool __must_check IS_ERR(__force const void *ptr)

Fix it with the proper include.

Signed-off-by: Julien Thierry <julien.thierry@arm.com>